### ISSUE TITLE
Stuff with an axis placement

### ISSUE THREAD

**Issue by mworzala** [hollow-cube/mapmaker#102]
```[tasklist]
### Tasks
- [x] Logs (+ stripped logs)
- [x] Basalt
- [x] Bone block
- [x] Muddy mangrove roots
- [x] All terracotta
- [x] Quartz pillars
- [x] Purpur pillars
- [x] Warped Hyphae (this is a log apparently)
- [x] Deepslate
- [x] Polished basalt
- [x] Carved pumpkins (+ jack o lanterns)
- [x] Bee nest
- [x] Dropper (faces up at <45 degrees pitch, down at -45)
- [x] Dispenser
- [x] Observer
- [x] Lightning rods
- [x] Chain
- [x] Furnace + other stuff like that
- [x] End rods
- [x] Torches
- [x] Beehive
- [x] Command block
- [x] Redstone comparator
- [x] Redstone repeater
- [ ] https://github.com/hollow-cube/mapmaker/issues/109
```
