### ISSUE TITLE
Stuff with fancy shift right clicks

### ISSUE THREAD

**Issue by mworzala** [hollow-cube/mapmaker#103]
```[tasklist]
### Tasks
- [x] Redstone lamp
- [x] Piston body
- [x] iron trapdoor
- [ ] https://github.com/hollow-cube/mapmaker/issues/110
- [x] campfire with hand toggles fire
- [x] Composter cycle fill state
- [x] candle light state
- [x] cake should cycle
- [x] candle cake should light
- [x] Open barrel
- [ ] https://github.com/hollow-cube/mapmaker/issues/107
- [x] right click slab to flip to other state (top/bottom)
- [x] fence gate opening
- [x] place book in lectern
- [x] piston toggle extended
```
