### ISSUE TITLE
Chat (v1)

### ISSUE THREAD

**Issue by mworzala** [hollow-cube/mapmaker#133]
```[tasklist]
### Tasks
- [ ] staff wrench badge: developer
- [ ] staff shield badge: moderator
- [ ] staff block badge: creative team
- [ ] default user chat and color
- [ ] /message, /msg, /tell
- [ ] /reply, /r
- [ ] /chat staff, /chat s, /c s to toggle staff chat on
- [ ] /staffchat, /sc to send a single message in staff chat
- [ ] /chat all, /chat a, /c a to toggle global chat on
- [ ] /allchat, /ac to send a single message in global chat
- [ ] /chat local, /chat l, /c l to toggle local chat on (specific to your world/instance)
- [ ] /localchat, /lc to send a single message in your local chat
```
notes:
- staff badges are prefix icons to a person's name. You can only have one. If you are a developer and designer, but you mostly do development, then you would have the wrench developer badge.
- ranks determine a person's username and badge color (admins red, seniors blue, juniors lime) Hex colors for those names are in the placeholders resources file in the main repo)
