### ISSUE TITLE
legacy map importing

### ISSUE THREAD

**Issue by sethhargis28** [hollow-cube/mapmaker#134]
let people import their old maps from omega to the new version, either to touch up and publish in their slots or download 
```[tasklist]
### Tasks
- [ ] https://github.com/hollow-cube/mapmaker/issues/139
- [ ] https://github.com/hollow-cube/mapmaker/issues/138
- [ ] https://github.com/hollow-cube/mapmaker/issues/137
- [ ] https://github.com/hollow-cube/mapmaker/issues/100
```
