### ISSUE TITLE
Building map issues

### ISSUE THREAD

**Issue by mworzala** [hollow-cube/mapmaker#238]
```[tasklist]
### Tasks
- [x] Players are hidden when nearby
- [x] Toptimes command works at all
- [x] Replays are saved
- [x] Hotbar is trash
- [x] You should be able to fly
- [x] There should be no spectator mode
```
