### ISSUE TITLE
water block placement

### ISSUE THREAD

**Issue by Nixotica** [hollow-cube/mapmaker#247]
```[tasklist]
### Tasks
- [ ] Can place water above/below other water blocks
- [ ] Can place water next to other water blocks
- [ ] Can place water corner to other water
```
