### ISSUE TITLE
Placement rules pre-beta issues 

### ISSUE THREAD

**Issue by Nixotica** [hollow-cube/mapmaker#279]
```[tasklist]
### Tasks
- [x] Clickable doors cannot stay in open position
- [x] Slab doesn't place on top of same slab from above (works from below)
- [x] Placing on top of bottom of slab replaces it instead of placing it above/below it with gap
- [ ] https://github.com/hollow-cube/mapmaker/issues/408
- [x] Shulker box should be able to assume all 6 placement directions opposite block placed against
- [x] Snow can't pile on itself
- [x] Weeping vines don't connect and resize when placed below
- [x] Twisting vines don't connect and resize when placed above
- [x] Vines always place the full block version even on walls and ceiling
- [x] Large fern, peony, pitcher plant are only one block tall
- [x] Chrous plant doesn't connect to itself
- [x] Shift clicking pistons and sticky pistons removes the head, when it should extend it out, because when it is extended, you can left click to break either the base or the head, to get whichever part you want
- [x] infested block forms like infested deepslate
- [ ] https://github.com/hollow-cube/mapmaker/issues/407
- [x] right clicking a redstone comparator or repeater with a block places it on top (this is just generally a thing with a lot of other interactions like daylight sensors and lecterns)
- [x] levers
- [x] chiseled bookshelves
- [x] barrel
- [x] end portal frame + eye of ender
- [x] all anvil types
- [x] lanterns, hanging
- [x] kelp
- [x] coral, etc. without automatically being waterlogged
- [ ] https://github.com/hollow-cube/mapmaker/issues/409
- [x] Glow lichen always place the full block version even on floor, walls, ceiling
- [ ] https://github.com/hollow-cube/mapmaker/issues/410
- [x] Turtle eggs don't stack
- [x] Cocoa beans don't face any specific direction
- [x] Sea pickles aren't stackable
- [x] Skulk vein always places the full block version even on floor, walls, ceiling
```
