### ISSUE TITLE
Item frames (+ glowing) (entity)

### ISSUE THREAD

**Issue by BomBardyGamer** [hollow-cube/mapmaker#359]
```[tasklist]
### Tasks
- [x] Item Frame placement (interaction) rule
- [x] Items in frames
- [x] Item frame rotation
- [ ] https://github.com/hollow-cube/mapmaker/issues/360
```
