### ISSUE TITLE
Hypercube

### ISSUE THREAD

**Issue by mworzala** [hollow-cube/mapmaker#373]
```[tasklist]
### Tasks
- [x] Actually store it
- [x] Apply it from Tebex payments
- [x] Delete it when it expires
- [ ] Chat badge + color
- [ ] https://github.com/hollow-cube/mapmaker/issues/372
```
