### ISSUE TITLE
Store

### ISSUE THREAD

**Issue by mworzala** [hollow-cube/mapmaker#376]
```[tasklist]
### Tasks
- [ ] Book confirm GUI
- [ ] Book upsell GUI
- [ ] Store GUI
- [x] Correctly process Tebex payments
- [ ] https://github.com/hollow-cube/mapmaker/issues/370
- [ ] https://github.com/hollow-cube/mapmaker/issues/373
- [ ] https://github.com/hollow-cube/mapmaker/issues/375
```
