### ISSUE TITLE
Checkpoint/Status Plates

### ISSUE THREAD

**Issue by mworzala** [hollow-cube/mapmaker#377]
```[tasklist]
### Tasks
- [x] Editor GUI/art
- [x] Storage of effects/functionality
- [x] Potion Effects
- [x] Teleportation
- [x] Elytra (?)
- [ ] Trident (?)
- [ ] Toggle Map Settings
- [x] Single precise coordinates (Use teleport for now)
- [x] Resetting height
- [x] Time limit
- [x] Checkpoint lives
```
