### ISSUE TITLE
Map Settings

### ISSUE THREAD

**Issue by mworzala** [hollow-cube/mapmaker#380]
```[tasklist]
### Tasks
- [x] Disable spectator mode
- [ ] https://github.com/hollow-cube/mapmaker/issues/419
```

OLD UNFORMATTED ONES BELOW NOT SURE WHICH WILL BE DONE

- [ ] no turning
- [ ] take damage
- [ ] reset on damage (needs take damage toggled on)
- [ ] reset in lava
- [ ] reset in water
- [ ] place blocks (gives you blocks at the start of maps, maybe at certain checkpoints too, and only allows them to be placed on specific blocks. Useful for certain parkour maps, especially gauntlet types. Needs to be talked about and thought on more. ITMG would have the best ideas for this probably)
- [ ] disable savestates (can disable savestates so your current one gets deleted every time you leave a map. Useful for if a certain jump requires no falling momentum and leaving and rejoining the map lets you get that and cheese it with no setup. If you can keep your momentum in your savestate, that would fix this issue and this entire setting wouldn't be necessary then. Another, and probably better alternative, is allowing for checkpoint savestates, so you go back to your last checkpoint if you ever leave and rejoin the map)
