### ISSUE TITLE
Features required to put spawn world in mapmaker dev server

### ISSUE THREAD

**Issue by mworzala** [hollow-cube/mapmaker#97]
```[tasklist]
### Tasks required to move the Map Maker spawn into a Map Maker world on the dev server.
- [x] Block placement rules (not all, but most: all rotations/facings and block states probably)
- [x] Wand
- [x] Move
- [x] Stack
- [x] Copy
- [x] Cut
- [x] Rotate (90-degree angles)
- [x] Paste
- [x] Undo
- [x] Redo
- [x] Pos1
- [x] Pos2
- [x] Loft
- [x] Set
- [x] Replace
- [x] Flip
- [x] Clearclipboard
- [x] Debugstick
- [ ] https://github.com/hollow-cube/mapmaker/issues/100
```
